# Generated by Django 4.1 on 2022-09-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=5)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_field', models.CharField(default='cse', max_length=10)),
            ],
        ),
    ]
